name: Auto Swap Staging to Production

on:
  push:
    branches:
      - appServiceSlot_Working_DO_NOT_MERGE

jobs:
  swap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Swap staging slot to production
        run: |
          az webapp deployment slot swap \
            --resource-group cloudboosta-bluegreen-rg \
            --name cloudboosta-bluegreen-webapp-1234 \
            --slot staging \
            --target-slot production
